mainpage/urls.py
from django.urls import path

from . import views
app_name = 'mainpage'
urlpatterns = [
    path('',views.mainpage, name='mainpage'),
    path('Contact',views.contact, name='contact'),
]

will/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',include('mainpage.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainpage/models.py
from django.db import models



class Quotes(models.Model):
    quote = models.CharField(max_length=256)
    cite = models.CharField(max_length=32)
    
    def __str__(self):
        return self.quote + '  from   '+self.cite

mainpage/views.py
from django.shortcuts import render
from .models import Quotes

import random
# Create your views here


def mainpage(request):
    q = random.choice(Quotes.objects.all())
    return render(request,'mainpage.html',{'Quote':q})

def contact(request):
    return render(request,'contact.html')

mainpage/templates/base.html
<!doctype html>
<html lang="zh">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% load static %}
    <link rel="stylesheet" type="text/css"  href="{% static 'mainpage/main.css' %}">
    <link herf ="/static/mainpage/main.css">

    <title>渌滨小站</title>
   
  </head>
  <body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
              <div class="col-4 pt-1">
                <a class="text-muted" href="{% url 'mainpage:mainpage' %}">Welcome</a>
              </div>
              <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{% url 'mainpage:mainpage' %}">渌滨小站</a>
              </div>
              <div class="col-4 d-flex justify-content-end align-items-center">
                <!-- <a class="text-muted" href="#" aria-label="Search">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                </a> -->
                <!-- <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a> -->
              </div>
            </div>
        </header>
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
              <a class="p-2 text-muted" href="#">博文</a>
              <a class="p-2 text-muted" href="/Contact">关于</a>
            </nav>
          </div>
          {% block jumbotron %}
         
          {% endblock %}
        <!-- <div class="row mb-2">
            <div class="col-md-6">
              <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                  <strong class="d-inline-block mb-2 text-primary">World</strong>
                  <h3 class="mb-0">Featured post</h3>
                  <div class="mb-1 text-muted">Nov 12</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                  <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                  <strong class="d-inline-block mb-2 text-success">Design</strong>
                  <h3 class="mb-0">Post title</h3>
                  <div class="mb-1 text-muted">Nov 11</div>
                  <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                  <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div> -->
    <main role="main" class="container">
        {% block main %}
        
        {% endblock %}
    </main>
    
    <footer class="blog-footer">
        <div class="inner">
            <p>Powered by <a href="http://getbootstrap.com/">Bootstrap</a> and django.</a></p>
        </div>
    </footer>


    






    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

mainpage/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block jumbotron %}
{% endblock %}
{% block main %}
<div class="row justify-content-center">
  <div class="card" style="width: 18rem;">
    <img src="{% static 'images/contact.jpeg' %}" class="card-img-top" alt="奶奶门前的鱼塘">
    <div class="card-body">
      <p class="card-text">南阳桥奶奶家门前的鱼塘，承载了很多记忆的地方。</p>
      <address>
  
  
  
        <strong>杨 晓葵</strong><br>
      
      
      
        <a href="mailto:#">williamyang0211@outlook.com</a>
      
      
      
      </address>
      </div>
    </div>
  </div>
{% endblock %}

mainpage/templates/mainpage.html
{% extends "base.html" %}
{% load static %}
{% block jumbotron %}
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
  <img src="{% static 'images/mainpage.jpeg' %}" class="card-img-top" alt="">
  <div class="col-md-6 px-0">
    <p class="lead my-3">{{Quote.quote}}</p>
              <p class="lead mb-0"><cite title="Source Title" class='blockquote-reverse'>{{Quote.cite}}</cite></p>
  
   
  </div>
</div>
              
{% endblock %}
{% block main %}



{% endblock %}